# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '23' 
          distribution: 'temurin'
          cache: maven

      - name: Make chromedriver executable
        run: chmod +x ./drivers/chromedriver

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn verify -DbrowserName=${{ github.event.inputs.browserName || 'chrome' }}

      - name: Get Allure history
        uses: actions/checkout@v3
        if: steps.build.outcome == 'success'
        continue-on-error: true
        with:
            ref: gh-pages
            path: gh-pages
    
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: steps.build.outcome == 'success'
        id: allure-report
        with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
                  
      - name: Generate Allure report
        run: mvn allure:report
        if: success()

      - name: Deploy report to Github Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
             target_branch: gh-pages
             build_dir: allure-history
        env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
